/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import models.User;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author USER
 */
public class AdminDashboardForm extends javax.swing.JFrame {
    
    private User currentUser;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboardForm(User user) {
        this.currentUser = user;
        initComponents();
        
        
        jLabel1.setText(
        "Login Sebagai : " + currentUser.getUsername() +
        " (" + currentUser.getRole() + ")"
        );
        
        // Setup form panels
        setPanel(jPanel3, mahasiswaManagementForm);
        setPanel(jPanel4, alatManagementForm);
        alatManagementForm.setPeminjamanForm(peminjamanForm);

        setPanel(jPanel5, peminjamanForm);
        peminjamanForm.setPengembalianForm(pengembalianForm);
        peminjamanForm.setAlatManagementForm(alatManagementForm);

        setPanel(jPanel6, pengembalianForm);
        pengembalianForm.setLaporanForm(laporanForm);
        pengembalianForm.setAlatManagementForm(alatManagementForm);

        setPanel(jPanel7, laporanForm);
        
        // Load initial data
        laporanForm.loadLaporan();
        peminjamanForm.loadAlatTersedia();
        pengembalianForm.loadData();
        alatManagementForm.loadData();
        mahasiswaManagementForm.loadData();
    }

    private AdminDashboardForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // ===== HELPER =====
    private void setPanel(JPanel container, JPanel content) {
        container.setLayout(new BorderLayout());
        container.removeAll();
        container.add(content, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDashboard = new javax.swing.JPanel();
        jPanelContent = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelContent = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        mahasiswaManagementForm = new gui.MahasiswaManagementForm();
        jPanel4 = new javax.swing.JPanel();
        alatManagementForm = new gui.AlatManagementForm();
        jPanel5 = new javax.swing.JPanel();
        peminjamanForm = new gui.PeminjamanForm();
        jPanel6 = new javax.swing.JPanel();
        pengembalianForm = new gui.PengembalianForm();
        jPanel7 = new javax.swing.JPanel();
        laporanForm = new gui.LaporanForm();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuLogin = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard - Sistem Peminjaman Alat");
        setPreferredSize(new java.awt.Dimension(1400, 700));
        setResizable(false);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Login Sebagai : -");
        jPanel2.add(jLabel1);

        jTabbedPane1.addChangeListener(this::jTabbedPane1StateChanged);

        jLabelTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("SELAMAT DATANG, ADMIN!");

        jLabelContent.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabelContent.setForeground(new java.awt.Color(0, 0, 0));
        jLabelContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContent.setText("Anda memiliki akses penuh ke sistem:");

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabelContent)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 180));

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jList1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "- Kelola Mahasiswa (CRUDS)", "- Kelola Alat (CRUDS)", "- Peminjaman", "- Pengembalian", "- Laporan" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );

        jTabbedPane1.addTab("Dashboard", jPanelDashboard);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(mahasiswaManagementForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Kelola Mahasiswa", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(alatManagementForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Kelola Alat", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(peminjamanForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Peminjaman", jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(pengembalianForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Pengembalian", jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(laporanForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Laporan", jPanel7);

        jMenu3.setText("File");

        jMenuLogin.setText("Logout");
        jMenuLogin.addActionListener(this::jMenuLoginActionPerformed);
        jMenu3.add(jMenuLogin);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(this::jMenuExitActionPerformed);
        jMenu3.add(jMenuExit);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem3.setText("About");
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_jMenuLoginActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 1) {
            mahasiswaManagementForm.loadData();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    
  
    private void logout() {
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            new LoginForm().setVisible(true);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.AlatManagementForm alatManagementForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContent;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.LaporanForm laporanForm;
    private gui.MahasiswaManagementForm mahasiswaManagementForm;
    private gui.PeminjamanForm peminjamanForm;
    private gui.PengembalianForm pengembalianForm;
    // End of variables declaration//GEN-END:variables
}
