/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.AlatDAO;
import models.Alat;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author USER
 */
public class AlatManagementForm extends javax.swing.JPanel {
    
    
    private DefaultTableModel tableModel;
    private AlatDAO alatDAO;
    private PeminjamanForm peminjamanForm;


    /**
     * Creates new form AlatManagementForm
     */
    public AlatManagementForm() {
        alatDAO = new AlatDAO();
        initComponents();
        tableModel = (DefaultTableModel) jTable2.getModel();

        jButtonAdd.addActionListener(this::tambahAlat);
        jButtonUpdate.addActionListener(this::editAlat);
        jButtonDelete.addActionListener(this::hapusAlat);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(574, 419));

        jTable2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Kategori", "Stok", "Tersedia"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel7.setText("Kelola Alat");
        jPanel13.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel8.setText("Cari : ");
        jPanel14.add(jLabel8);

        txtSearch.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel14.add(txtSearch);

        jButtonSearch.setText("Cari");
        jButtonSearch.setPreferredSize(new java.awt.Dimension(60, 23));
        jButtonSearch.addActionListener(this::jButtonSearchActionPerformed);
        jPanel14.add(jButtonSearch);

        jButtonAdd.setText("Tambah");
        jPanel15.add(jButtonAdd);

        jButtonUpdate.setText("Edit");
        jPanel15.add(jButtonUpdate);

        jButtonDelete.setText("Hapus");
        jPanel15.add(jButtonDelete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    
    public void loadData() {
        tableModel.setRowCount(0);
        for (Alat a : alatDAO.getAllAlat()) {
            tableModel.addRow(new Object[]{
                    a.getKode(),
                    a.getNama(),
                    a.getKategori(),
                    a.getStok(),
                    a.getTersedia()
            });
        }
    }
    
    public void searchData() {
        String keyword = txtSearch.getText().trim().toLowerCase();
        if (keyword.isEmpty()) {
            loadData();
            return;
        }

        tableModel.setRowCount(0);
        for (Alat a : alatDAO.getAllAlat()) {
            if (a.getKode().toLowerCase().contains(keyword)
                    || a.getNama().toLowerCase().contains(keyword)
                    || a.getKategori().toLowerCase().contains(keyword)) {

                tableModel.addRow(new Object[]{
                        a.getKode(),
                        a.getNama(),
                        a.getKategori(),
                        a.getStok(),
                        a.getTersedia()
                });
            }
        }
    }

    /* ===================== CRUD ===================== */

    public void tambahAlat(ActionEvent evt) {
        JDialog dialog = createDialog("Tambah Alat");
        JPanel panel = createFormPanel();

        JTextField txtKode = new JTextField();
        JTextField txtNama = new JTextField();
        JComboBox<String> comboKategori = new JComboBox<>(
                new String[]{"Elektronik", "Alat Tulis", "Lab Komputer", "Perlengkapan"});
        JTextField txtStok = new JTextField("0");

        panel.add(new JLabel("Kode:")); panel.add(txtKode);
        panel.add(new JLabel("Nama:")); panel.add(txtNama);
        panel.add(new JLabel("Kategori:")); panel.add(comboKategori);
        panel.add(new JLabel("Stok:")); panel.add(txtStok);

        JButton btnSimpan = new JButton("Simpan");
        btnSimpan.addActionListener(e -> {
            try {
                Alat alat = new Alat(
                        txtKode.getText().trim(),
                        txtNama.getText().trim(),
                        comboKategori.getSelectedItem().toString(),
                        Integer.parseInt(txtStok.getText().trim())
                );

                if (alatDAO.addAlat(alat)) {
                    JOptionPane.showMessageDialog(dialog, "Alat berhasil ditambahkan!");
                    dialog.dispose();
                    refreshAfterChange();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, "Input tidak valid!");
            }
        });

        showDialog(dialog, panel, btnSimpan);
    }

    public void editAlat(ActionEvent evt) {
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih alat terlebih dahulu!");
            return;
        }

        Alat alat = alatDAO.getAlatByKode((String) tableModel.getValueAt(row, 0));
        if (alat == null) return;

        JDialog dialog = createDialog("Edit Alat");
        JPanel panel = createFormPanel();

        JTextField txtNama = new JTextField(alat.getNama());
        JTextField txtKategori = new JTextField(alat.getKategori());
        JTextField txtStok = new JTextField(String.valueOf(alat.getStok()));

        panel.add(new JLabel("Nama:")); panel.add(txtNama);
        panel.add(new JLabel("Kategori:")); panel.add(txtKategori);
        panel.add(new JLabel("Stok:")); panel.add(txtStok);

        JButton btnSimpan = new JButton("Simpan");
        btnSimpan.addActionListener(e -> {
            try {
                alat.setNama(txtNama.getText().trim());
                alat.setKategori(txtKategori.getText().trim());
                alat.setStok(Integer.parseInt(txtStok.getText().trim()));

                if (alatDAO.updateAlat(alat)) {
                    JOptionPane.showMessageDialog(dialog, "Data diperbarui!");
                    dialog.dispose();
                    refreshAfterChange();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, "Input tidak valid!");
            }
        });

        showDialog(dialog, panel, btnSimpan);
    }

    public void hapusAlat(ActionEvent evt) {
        int row = jTable2.getSelectedRow();
        if (row == -1) return;

        String kode = (String) tableModel.getValueAt(row, 0);
        if (JOptionPane.showConfirmDialog(this,
                "Hapus alat " + kode + "?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            if (alatDAO.deleteAlat(kode)) {
                JOptionPane.showMessageDialog(this, "Alat dihapus!");
                refreshAfterChange();
            }
        }
    }
    
private void refreshAfterChange() {
        loadData();
        if (peminjamanForm != null) {
            peminjamanForm.loadAlatTersedia();
        }
    }

    private JDialog createDialog(String title) {
        JDialog d = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), title, true);
        d.setSize(400, 300);
        d.setLocationRelativeTo(this);
        return d;
    }

    private JPanel createFormPanel() {
        JPanel p = new JPanel(new GridLayout(0, 2, 10, 10));
        p.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        return p;
    }

    private void showDialog(JDialog d, JPanel form, JButton btnSimpan) {
        JButton btnBatal = new JButton("Batal");
        btnBatal.addActionListener(e -> d.dispose());

        JPanel btnPanel = new JPanel();
        btnPanel.add(btnSimpan);
        btnPanel.add(btnBatal);

        d.setLayout(new BorderLayout());
        d.add(form, BorderLayout.CENTER);
        d.add(btnPanel, BorderLayout.SOUTH);
        d.setVisible(true);
    }

    public void setPeminjamanForm(PeminjamanForm peminjamanForm) {
        this.peminjamanForm = peminjamanForm;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
