/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import models.User;
import dao.MahasiswaDAO;
import models.Mahasiswa;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author USER
 */
public class MahasiswaDashboardForm extends javax.swing.JFrame {
    private User currentUser;
    private Mahasiswa mahasiswa;

    /**
     * Creates new form MahasiswaDashboard
     */
    public MahasiswaDashboardForm(User user) {
        this.currentUser = user;
        initComponents();
        
        loadMahasiswaData();
        
        // Inisialisasi form
        peminjamanForm = new PeminjamanForm();
        peminjamanForm.setMahasiswa(mahasiswa, false);
        
        pengembalianForm = new PengembalianForm(mahasiswa);
        peminjamanForm.setPengembalianForm(pengembalianForm);
        
        riwayatForm = new RiwayatForm(mahasiswa);
        pengembalianForm.setRiwayatForm(riwayatForm);
        
        // Setup panel
        setPanel(jPanelPinjaman, peminjamanForm);
        peminjamanForm.loadAlatTersedia();

        setPanel(jPanelPengembalian, pengembalianForm);
        pengembalianForm.loadData();

        setPanel(jPanelRiwayat, riwayatForm);
        riwayatForm.loadRiwayat();
        
        
        txtNim.setText(": " + mahasiswa.getNim());
        txtNama.setText(": " +mahasiswa.getNama());
        txtJurusan.setText(": " + mahasiswa.getJurusan());
        txtFooter.setText("Login Sebagai : " + mahasiswa.getNama() + " (" + user.getRole() + ")");
        
        setLocationRelativeTo(null);
    }

    private MahasiswaDashboardForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
    private void loadMahasiswaData() {
        MahasiswaDAO dao = new MahasiswaDAO();
        // Asumsi username adalah NIM
        this.mahasiswa = dao.getMahasiswaByNim(currentUser.getUsername());
    }
    
      // ===== HELPER =====
    private void setPanel(JPanel container, JPanel content) {
        container.setLayout(new BorderLayout());
        container.removeAll();
        container.add(content, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDashboard = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jPanelProfil = new javax.swing.JPanel();
        lblNim = new javax.swing.JLabel();
        txtNim = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        lblJurusan = new javax.swing.JLabel();
        txtJurusan = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        txtFooter = new javax.swing.JLabel();
        jPanelPinjaman = new javax.swing.JPanel();
        peminjamanForm = new gui.PeminjamanForm();
        jPanelPengembalian = new javax.swing.JPanel();
        pengembalianForm = new gui.PengembalianForm();
        jPanelRiwayat = new javax.swing.JPanel();
        riwayatForm = new gui.RiwayatForm();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAHASISWA DASHBOARD");
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanelDashboard.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDashboard.setLayout(new java.awt.BorderLayout());

        jPanelHeader.setBackground(new java.awt.Color(102, 102, 102));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(234, 50));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitle.setText("SELAMAT DATANG!");
        jPanelHeader.add(txtTitle);

        jPanelDashboard.add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jPanelProfil.setBackground(new java.awt.Color(153, 153, 153));
        jPanelProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profil Mahasiswa", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblNim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNim.setText("Nim");
        lblNim.setIconTextGap(1);

        txtNim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNim.setText("Tes");

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNama.setText("Nama");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNama.setText("Tes");

        lblJurusan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJurusan.setText("Jurusan");

        txtJurusan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJurusan.setText("Tes");

        javax.swing.GroupLayout jPanelProfilLayout = new javax.swing.GroupLayout(jPanelProfil);
        jPanelProfil.setLayout(jPanelProfilLayout);
        jPanelProfilLayout.setHorizontalGroup(
            jPanelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtJurusan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(598, 598, 598))
        );
        jPanelProfilLayout.setVerticalGroup(
            jPanelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfilLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNim)
                    .addComponent(txtNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJurusan)
                    .addComponent(txtJurusan))
                .addGap(253, 253, 253))
        );

        jPanelInfo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanelInfo.setLayout(new javax.swing.BoxLayout(jPanelInfo, javax.swing.BoxLayout.Y_AXIS));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Anda dapat");
        jPanelInfo.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("• Meminjam alat lab");
        jPanelInfo.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("• Mengembalikan alat");
        jPanelInfo.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("• Melihat riwayat peminjaman");
        jPanelInfo.add(jLabel9);

        jPanelFooter.setBackground(new java.awt.Color(102, 102, 102));
        jPanelFooter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtFooter.setText("Status Login");
        jPanelFooter.add(txtFooter);

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContentLayout.createSequentialGroup()
                        .addComponent(jPanelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelDashboard.add(jPanelContent, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Dashboard", jPanelDashboard);

        jPanelPinjaman.setLayout(new java.awt.BorderLayout());

        peminjamanForm.setBackground(new java.awt.Color(102, 102, 102));
        jPanelPinjaman.add(peminjamanForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Pinjaman", jPanelPinjaman);

        jPanelPengembalian.setLayout(new java.awt.BorderLayout());
        jPanelPengembalian.add(pengembalianForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Pengembalian", jPanelPengembalian);

        jPanelRiwayat.setLayout(new java.awt.BorderLayout());
        jPanelRiwayat.add(riwayatForm, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Riwayat", jPanelRiwayat);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("File");

        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(this::jMenuLogoutActionPerformed);
        jMenu1.add(jMenuLogout);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(this::jMenuExitActionPerformed);
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed
    
    private void logout() {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            new LoginForm().setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MahasiswaDashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelPengembalian;
    private javax.swing.JPanel jPanelPinjaman;
    private javax.swing.JPanel jPanelProfil;
    private javax.swing.JPanel jPanelRiwayat;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private gui.PeminjamanForm peminjamanForm;
    private gui.PengembalianForm pengembalianForm;
    private gui.RiwayatForm riwayatForm;
    private javax.swing.JLabel txtFooter;
    private javax.swing.JLabel txtJurusan;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtNim;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
