/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.MahasiswaDAO;
import models.Mahasiswa;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author USER
 */
public class MahasiswaManagementForm extends javax.swing.JPanel {

    private final MahasiswaDAO mahasiswaDAO;
    private DefaultTableModel tableModel;
    
    
    public MahasiswaManagementForm() {
        mahasiswaDAO = new MahasiswaDAO();
        initComponents();
        
        tableModel = (DefaultTableModel) jTable1.getModel();
        
        jButtonAdd.addActionListener(this::tambahMahasiswa);
        jButtonUpdate.addActionListener(this::editMahasiswa);
        jButtonDelete.addActionListener(this::hapusMahasiswa);
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel4.setText("Kelola Data Mahasiswa");
        jPanel9.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel5.setText("Cari : ");
        jPanel10.add(jLabel5);

        txtSearch.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel10.add(txtSearch);

        jButtonSearch.setText("Cari");
        jButtonSearch.setPreferredSize(new java.awt.Dimension(60, 23));
        jButtonSearch.addActionListener(this::jButtonSearchActionPerformed);
        jPanel10.add(jButtonSearch);

        jButtonAdd.setText("Tambah");
        jPanel11.add(jButtonAdd);

        jButtonUpdate.setText("Edit");
        jPanel11.add(jButtonUpdate);

        jButtonDelete.setText("Hapus");
        jPanel11.add(jButtonDelete);

        jTable1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jurusan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    
    public final void loadData() {
        List<Mahasiswa> list = mahasiswaDAO.getAllMahasiswa();
        tableModel.setRowCount(0);

        for (Mahasiswa mhs : list) {
            tableModel.addRow(new Object[]{
                mhs.getNim(),
                mhs.getNama(),
                mhs.getJurusan()
            });
        }
    }
    
    public void searchData() {
        String keyword = txtSearch.getText().trim().toLowerCase();

        if (keyword.isEmpty()) {
            loadData();
            return;
        }

        tableModel.setRowCount(0);

        for (Mahasiswa mhs : mahasiswaDAO.getAllMahasiswa()) {
            if (mhs.getNim().toLowerCase().contains(keyword)
                    || mhs.getNama().toLowerCase().contains(keyword)
                    || mhs.getJurusan().toLowerCase().contains(keyword)) {

                tableModel.addRow(new Object[]{
                    mhs.getNim(),
                    mhs.getNama(),
                    mhs.getJurusan()
                });
            }
        }
    }
    
    public void tambahMahasiswa(ActionEvent evt) {
        JDialog dialog = createDialog("Tambah Mahasiswa");

        JTextField txtNim = new JTextField();
        JTextField txtNama = new JTextField();
        JComboBox<String> comboJurusan = new JComboBox<>(new String[]{
            "Informatika", "Sistem Informasi", "Teknik Komputer",
            "Manajemen", "Akuntansi", "Teknik Elektro"
        });

        JPanel panel = createFormPanel();
        panel.add(new JLabel("NIM:"));
        panel.add(txtNim);
        panel.add(new JLabel("Nama:"));
        panel.add(txtNama);
        panel.add(new JLabel("Jurusan:"));
        panel.add(comboJurusan);

        JButton btnSimpan = new JButton("Simpan");
        btnSimpan.addActionListener(e -> {
            if (txtNim.getText().isEmpty() || txtNama.getText().isEmpty()) { 
                JOptionPane.showMessageDialog(dialog, "Semua field harus diisi!"); 
                return; 
            }

            Mahasiswa mhs = new Mahasiswa(
                txtNim.getText().trim(),
                txtNama.getText().trim(),
                comboJurusan.getSelectedItem().toString()
            );

            if (mahasiswaDAO.addMahasiswa(mhs)) {
                JOptionPane.showMessageDialog(dialog, "Mahasiswa berhasil ditambahkan!");
                dialog.dispose();
                loadData();
            }
        });

        dialog.add(panel, BorderLayout.CENTER);
        dialog.add(createButtonPanel(btnSimpan, dialog), BorderLayout.SOUTH);
        dialog.setVisible(true);
    }
    
        public void editMahasiswa(ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih mahasiswa terlebih dahulu!");
            return;
        }

        String nim = tableModel.getValueAt(row, 0).toString();
        Mahasiswa mhs = mahasiswaDAO.getMahasiswaByNim(nim);

        if (mhs == null) {
            JOptionPane.showMessageDialog(this, "Data mahasiswa tidak ditemukan!");
            return;
        }

        JDialog dialog = createDialog("Edit Mahasiswa");

        JTextField txtNama = new JTextField(mhs.getNama());
        JTextField txtJurusan = new JTextField(mhs.getJurusan());

        JPanel panel = createFormPanel();
        panel.add(new JLabel("Nama:"));
        panel.add(txtNama);
        panel.add(new JLabel("Jurusan:"));
        panel.add(txtJurusan);

        JButton btnSimpan = new JButton("Simpan");
        btnSimpan.addActionListener(e -> {
            if (txtNama.getText().isEmpty() || txtJurusan.getText().isEmpty()) { 
                JOptionPane.showMessageDialog(dialog, "Semua field harus diisi!"); 
                return; 
            }

            mhs.setNama(txtNama.getText().trim());
            mhs.setJurusan(txtJurusan.getText().trim());

            if (mahasiswaDAO.updateMahasiswa(mhs)) {
                JOptionPane.showMessageDialog(dialog, "Data berhasil diperbarui!");
                dialog.dispose();
                loadData();
            }
        });

        dialog.add(panel, BorderLayout.CENTER);
        dialog.add(createButtonPanel(btnSimpan, dialog), BorderLayout.SOUTH);
        dialog.setVisible(true);
    }
    
    public void hapusMahasiswa(ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih mahasiswa terlebih dahulu!");
            return;
        }

        String nim = tableModel.getValueAt(row, 0).toString();
        String nama = tableModel.getValueAt(row, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Hapus mahasiswa " + nama + " (" + nim + ")?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            mahasiswaDAO.deleteMahasiswa(nim);
            loadData();
        }
    }
    
    private JDialog createDialog(String title) {
        JDialog dialog = new JDialog(
            (Frame) SwingUtilities.getWindowAncestor(this),
            title,
            true
        );
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout());
        return dialog;
    }

    private JPanel createFormPanel() {
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        return panel;
    }

    private JPanel createButtonPanel(JButton btnSimpan, JDialog dialog) {
        JButton btnBatal = new JButton("Batal");
        btnBatal.addActionListener(e -> dialog.dispose());

        JPanel panel = new JPanel(new FlowLayout());
        panel.add(btnSimpan);
        panel.add(btnBatal);
        return panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
