/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.AlatDAO;
import dao.TransaksiDAO;
import dao.MahasiswaDAO;
import models.Mahasiswa;
import models.Alat;
import models.Transaksi;

import javax.swing.*;
import java.awt.*;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;


/**
 *
 * @author USER
 */
public class PeminjamanForm extends javax.swing.JPanel {
    
    // ====== STATE ======
    private Mahasiswa mahasiswa;
    private boolean isAdmin;

    // ====== DAO ======
    private AlatDAO alatDAO;
    private TransaksiDAO transaksiDAO;
    private MahasiswaDAO mahasiswaDAO;

    // ====== RELASI FORM ======
    private PengembalianForm pengembalianForm;
    private AlatManagementForm alatManagementForm;

    
    /**
     * Creates new form PeminjamanForm
     */
    // ====== CONSTRUCTOR ======
    public PeminjamanForm(Mahasiswa mahasiswa, boolean isAdmin) {
        this.mahasiswa = mahasiswa;
        this.isAdmin = isAdmin;
        init();
    }

    public PeminjamanForm() {
        this(null, true); // default admin
    }

    private void init() {
        alatDAO = new AlatDAO();
        transaksiDAO = new TransaksiDAO();
        mahasiswaDAO = new MahasiswaDAO();

        initComponents();
        comboAlat.setRenderer(new AlatComboBoxRenderer());

        btnPinjam.setText(isAdmin ? "Proses Peminjaman (Admin)" : "Ajukan Peminjaman");
        updateStatusLabel();
    }

    // ====== SETTER SESSION ======
    public void setMahasiswa(Mahasiswa mahasiswa, boolean isAdmin) {
        this.mahasiswa = mahasiswa;
        this.isAdmin = isAdmin;

        btnPinjam.setText(isAdmin ? "Proses Peminjaman (Admin)" : "Ajukan Peminjaman");
        updateStatusLabel();
        loadAlatTersedia();
    }

    private void updateStatusLabel() {
        if (!isAdmin && mahasiswa != null) {
            jLabelStatus.setText(
                "Status: Login sebagai " + mahasiswa.getNama() +
                " (" + mahasiswa.getNim() + ")"
            );
        } else {
            String time = new SimpleDateFormat("HH:mm:ss").format(new java.util.Date());
            jLabelStatus.setText("Status: Login sebagai Admin | " + time);
        }
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboDurasi = new javax.swing.JComboBox<>();
        btnPinjam = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboAlat = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();

        jLabel1.setText("PINJAM ALAT");
        jPanel1.add(jLabel1);

        jLabel5.setText("Durasi :");

        comboDurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        btnPinjam.setText("Pinjam Alat");
        btnPinjam.addActionListener(this::btnPinjamActionPerformed);

        jLabel3.setText("Alat Tersedia");

        comboAlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAlat, 0, 485, Short.MAX_VALUE)
                    .addComponent(comboDurasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btnPinjam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelStatus.setText("Status: [loadData()] Loading... | Last Updated: 15:30:05");
        jPanel5.add(jLabelStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamActionPerformed
        // TODO add your handling code here:
        prosesPeminjaman();
    }//GEN-LAST:event_btnPinjamActionPerformed

    
    
    

    public void loadAlatTersedia() {
        comboAlat.removeAllItems();

        List<Alat> list = alatDAO.getAlatTersedia();
        if (list.isEmpty()) {
            comboAlat.addItem("Tidak ada alat tersedia");
            comboAlat.setEnabled(false);
            btnPinjam.setEnabled(false);
            jLabelStatus.setText("Status: Tidak ada alat tersedia");
            return;
        }

        comboAlat.addItem("-- Pilih Alat --");
        for (Alat a : list) comboAlat.addItem(a);

        comboAlat.setEnabled(true);
        btnPinjam.setEnabled(true);
        jLabelStatus.setText("Status: " + list.size() + " alat tersedia");
    }
    
    
private void prosesPeminjaman() {
        if (comboAlat.getSelectedIndex() <= 0) { 
            JOptionPane.showMessageDialog(this, "Silakan pilih alat!"); 
            return; 
        }

        Alat alat = (Alat) comboAlat.getSelectedItem();
        int durasi = Integer.parseInt(comboDurasi.getSelectedItem().toString());

        if (!isAdmin) {
            simpanPeminjamanMahasiswa(alat, durasi);
        } else {
            simpanPeminjamanAdmin(alat, durasi);
        }

        resetForm();
    }

    
    private void simpanPeminjamanMahasiswa(Alat alat, int durasi) {
        Transaksi trx = new Transaksi(
            alat.getKode(),
            mahasiswa.getNim(),
            new Date(System.currentTimeMillis()),
            durasi
        );

        if (transaksiDAO.addTransaksiMahasiswa(trx, mahasiswa)) {
            alatDAO.updateStok(alat.getKode(), -1);
            notifyAfterPeminjaman();
            JOptionPane.showMessageDialog(this, "Peminjaman berhasil diajukan!");
        }
    }


    private void simpanPeminjamanAdmin(Alat alat, int durasi) {
        String nim = JOptionPane.showInputDialog(this, "Masukkan NIM Mahasiswa:");
        if (nim == null) return;

        Mahasiswa mhs = mahasiswaDAO.getMahasiswaByNim(nim.trim());
        if (mhs == null) {
            JOptionPane.showMessageDialog(this, "Mahasiswa tidak ditemukan!");
            return;
        }

        Transaksi trx = new Transaksi(
            alat.getKode(),
            mhs.getNim(),
            new Date(System.currentTimeMillis()),
            durasi
        );

        if (transaksiDAO.addTransaksiAdmin(trx)) {
            alatDAO.updateStok(alat.getKode(), -1);
            notifyAfterPeminjaman();
            JOptionPane.showMessageDialog(this, "Peminjaman berhasil diproses!");
        }
    }
    
    private void resetForm() {
        comboAlat.setSelectedIndex(0);
        comboDurasi.setSelectedIndex(0);
        loadAlatTersedia();
    }

    private void notifyAfterPeminjaman() {
        if (pengembalianForm != null) pengembalianForm.loadData();
        if (alatManagementForm != null) alatManagementForm.loadData();
    }


    public void setPengembalianForm(PengembalianForm f) {
        this.pengembalianForm = f;
    }

    public void setAlatManagementForm(AlatManagementForm f) {
        this.alatManagementForm = f;
    }


    class AlatComboBoxRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(
                JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {

            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if (value instanceof Alat a) {
                setText(a.getKode() + " - " + a.getNama() +
                        " [Tersedia: " + a.getTersedia() + "]");
                setForeground(a.getTersedia() > 0 ? Color.BLACK : Color.RED);
            }
            return this;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPinjam;
    private javax.swing.JComboBox<Object> comboAlat;
    private javax.swing.JComboBox<String> comboDurasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
