/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.AlatDAO;
import dao.TransaksiDAO;
import models.Alat;
import models.Mahasiswa;
import models.Transaksi;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author USER
 */
public class PengembalianForm extends javax.swing.JPanel {
    
    private Mahasiswa mahasiswa;
    private boolean isAdminMode = false;
    
    private TransaksiDAO transaksiDAO;
    private AlatDAO alatDAO;
    
    private AlatManagementForm alatManagementForm;
    private RiwayatForm riwayatForm;
    private LaporanForm laporanForm;

    private List<Transaksi> listTransaksiAktif;
    
    public PengembalianForm() {
        initDAO();
        initComponents();
        setupAdminMode();
    }
    
    public PengembalianForm(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
        this.isAdminMode = false;
        initDAO();
        initComponents();
        setupMahasiswaMode();
    }
    
    private void initDAO() {
        transaksiDAO = new TransaksiDAO();
        alatDAO = new AlatDAO();
    }
    
    private void setupAdminMode() {
        isAdminMode = true;
        lblMode.setText("");
        setupTableAdmin();
    }
    
    private void setupMahasiswaMode() {
        isAdminMode = false;

        if (mahasiswa != null) {
            lblMode.setText("Mode: Mahasiswa | " + mahasiswa.getNama()
                    + " | NIM: " + mahasiswa.getNim());
        } else {
            lblMode.setText("Mode: Mahasiswa - Data tidak tersedia");
        }

        setupTableMahasiswa();
    }
    
    // ================== TABLE SETUP ==================
    private void setupTableAdmin() {
        String[] columns = {
            "ID", "Nama Alat", "Mahasiswa",
            "Tanggal Pinjam", "Batas Kembali", "Status", "Denda (Rp)"
        };
        setTableModel(columns);
    }

    private void setupTableMahasiswa() {
        String[] columns = {
            "ID", "Nama Alat",
            "Tanggal Pinjam", "Batas Kembali", "Status", "Denda (Rp)"
        };
        setTableModel(columns);
    }

    private void setTableModel(String[] columns) {
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tableTransaksi.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMode = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblKondisi = new javax.swing.JLabel();
        comboKondisi = new javax.swing.JComboBox<>();
        btnKembalikan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORM PENGEMBALIAN ALAT");
        jPanel1.add(jLabel1);

        lblMode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMode.setText("Status Mode");
        jPanel2.add(lblMode);

        tableTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableTransaksi);

        lblKondisi.setText("Kondisi : ");

        comboKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak" }));

        btnKembalikan.setText("Kembalikan");
        btnKembalikan.addActionListener(this::btnKembalikanActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblKondisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(btnKembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKondisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnKembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblStatus.setText("Status Transaksi");
        jPanel4.add(lblStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalikanActionPerformed
        // TODO add your handling code here:
        prosesPengembalian();
    }//GEN-LAST:event_btnKembalikanActionPerformed
    
    // === PUBLIC METHODS ===
    
    public void loadData() {
        if (isAdminMode) {
            loadTransaksiAktifAdmin();
        } else {
            loadTransaksiAktifMahasiswa();
        }
        updateStatus();
    }

    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
        this.isAdminMode = false;
        setupMahasiswaMode();
        loadData();
    }

    public void setAdminMode(boolean adminMode) {
        this.isAdminMode = adminMode;
        if (adminMode) setupAdminMode();
        loadData();
    }
    
    // === PRIVATE METHODS ===
    
    private void loadTransaksiAktifAdmin() {
        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        model.setRowCount(0);

        listTransaksiAktif = transaksiDAO.getTransaksiAktif();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Transaksi trx : listTransaksiAktif) {
            trx.hitungDenda();
            model.addRow(new Object[]{
                trx.getId(),
                trx.getAlatNama(),
                trx.getMahasiswaNama(),
                sdf.format(trx.getTanggalPinjam()),
                sdf.format(trx.getBatasKembali()),
                trx.getStatus(),
                "Rp " + trx.getDenda()
            });
        }
    }
    
    private void loadTransaksiAktifMahasiswa() {
        if (mahasiswa == null) return;

        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        model.setRowCount(0);

        listTransaksiAktif = transaksiDAO.getTransaksiByMahasiswa(mahasiswa.getNim());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Transaksi trx : listTransaksiAktif) {
            if (!"Dipinjam".equals(trx.getStatus())) continue;

            trx.hitungDenda();
            model.addRow(new Object[]{
                trx.getId(),
                trx.getAlatNama(),
                sdf.format(trx.getTanggalPinjam()),
                sdf.format(trx.getBatasKembali()),
                trx.getStatus(),
                "Rp " + trx.getDenda()
            });
        }
    }
    
    private void updateStatus() {
        int total = listTransaksiAktif != null ? listTransaksiAktif.size() : 0;
        String time = new SimpleDateFormat("HH:mm:ss").format(new Date());
        lblStatus.setText("Status: " + total + " transaksi | " +
                (isAdminMode ? "Admin" : "Mahasiswa") +
                " | Update: " + time);
    }
    
    private void prosesPengembalian() {
        int row = tableTransaksi.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi!");
            return;
        }

        int id = Integer.parseInt(tableTransaksi.getValueAt(row, 0).toString());
        Transaksi trx = listTransaksiAktif.stream()
                .filter(t -> t.getId() == id)
                .findFirst().orElse(null);

        if (trx == null) return;

        trx.hitungDenda();
        trx.kembalikan();

        if (transaksiDAO.updateTransaksi(trx)) {
            alatDAO.updateStok(trx.getAlatCode(), 1);
            loadData();
            notifyAfterPengembalian();
            JOptionPane.showMessageDialog(this, "Pengembalian berhasil!");
        }
    }
    
    private void notifyAfterPengembalian() {
        if (riwayatForm != null) riwayatForm.loadRiwayat();
        if (laporanForm != null) laporanForm.loadLaporan();
        if (alatManagementForm != null) alatManagementForm.loadData();
    }
    
    public void setRiwayatForm(RiwayatForm f) { this.riwayatForm = f; }
    public void setLaporanForm(LaporanForm f) { this.laporanForm = f; }
    public void setAlatManagementForm(AlatManagementForm f) { this.alatManagementForm = f; }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembalikan;
    private javax.swing.JComboBox<String> comboKondisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKondisi;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
