/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.TransaksiDAO;
import models.Transaksi;
import models.Mahasiswa;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author USER
 */
public class RiwayatForm extends javax.swing.JPanel {

    private Mahasiswa mahasiswa;
    

    private TransaksiDAO transaksiDAO;
    
    
    /**
     * 
     * Creates new form RiwayatForm
     */
    public RiwayatForm(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
        this.transaksiDAO = new TransaksiDAO();
        initComponents();
    }
    
    public RiwayatForm(){
        this.transaksiDAO = new TransaksiDAO();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();

        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Nama Alat", "Tanggal Pinjam", "Tanggal Kembali", "Batas Tanggal Kembali", "Status", "Denda"
            }
        ));
        jScrollPane2.setViewportView(tblRiwayat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadRiwayat() {
        DefaultTableModel model = (DefaultTableModel) tblRiwayat.getModel();
        model.setRowCount(0);

        if (mahasiswa == null) {
            JOptionPane.showMessageDialog(this,
                "Data mahasiswa tidak tersedia",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            List<Transaksi> transaksiList =
                transaksiDAO.getTransaksiDikembalikanByMahasiswa(mahasiswa.getNim());

            for (Transaksi transaksi : transaksiList) {
                Object[] rowData = {
                    transaksi.getId(),
                    transaksi.getAlatNama(),
                    transaksi.getTanggalPinjam(),
                    transaksi.getTanggalKembali(),
                    transaksi.getBatasKembali(),
                    transaksi.getStatus(),
                    "Rp " + transaksi.getDenda()
                };
                model.addRow(rowData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error loading riwayat: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRiwayat;
    // End of variables declaration//GEN-END:variables
}
